### ISSUE TITLE
[TP logico] faltan los tests

### ISSUE THREAD

**Issue by MarianoSalerno** [LucasGaleano/paradigmas_TPs#24]

**Comment by kamipalomino** [comment]
corregido

**Comment by MarianoSalerno** [comment]
Una aclaracion con respecto a esto, testear hechos como miraSeries no tiene ningun sentido, esas cosas damos por sentado que funcionan porque sino tendriamos que probar las funcionalidades basicas de cada lenguaje con el que trabajamos (por ejemplo que funcione la suma, resta, etc). La idea de los tests es probar que los predicados/funciones/etc que codificamos nosotros funcionen, porque ahi es donde podemos meter la pata
