### ISSUE TITLE
[TP logico] mira series

### ISSUE THREAD

**Issue by MarianoSalerno** [LucasGaleano/paradigmas_TPs#25]
En logico si un predicado relaciona a un atomo con dos o mas preferimos escribirlo utilizando multiples clausulas en lugar de una lista para que el motor se encarge de relacionarlos en lugar de tener que trabajar extra nosotros desarmando la lista. Dicho sea de paso esto ultimo no lo hicieron, con lo cual ningun punto del TP funciona.

Ademas deberian ser coherentes con sus elecciones, si el predicado relaciona a juan, nico y maiu con una lista entonces a gaston deberia relacionarlo con una lista tambien, en este caso de un solo elemento

https://github.com/LucasGaleano/paradigmas_TPs/blob/748d288e0d84629376cb27d62480adb0ab5b1fbc/tp_l%C3%B3gico.pl#L4

**Comment by kamipalomino** [comment]
@MarianoSalerno tengo una duda sobre este tema,

-  miraSeries(nico, [starWars, got]) -> esto estaría mal 

-  miraSeries(nico, starWars) -> de esta se debería escribir? 
-  miraSeries(nico, got)

**Comment by MarianoSalerno** [comment]
@kamipalomino exactamente, es una clausula por cada serie, de esta forma prolog solito se encarga de barrerlas todas

**Comment by kamipalomino** [comment]
listo! corregido
