### ISSUE TITLE
[TP logico] sonPopulares

### ISSUE THREAD

**Issue by MarianoSalerno** [LucasGaleano/paradigmas_TPs#26]
Los predicados en logico se usan para relacionar atomos y/o para describir alguna propiedad que tenga alguno en particular, este predicado puntualmente se usa para describir que series son populares, con lo cual deberia ser de aridad 1 y tener multiples clausulas, una por cada serie que es popular. Ademas piensen que pasaria si el dia de mañana tengo que agregar mas series que sean populares, tendria que modificar todos los lugares donde aparezca este predicado para agregarle parametros, lo cual nos complica la solucion sin otorgarnos ningun beneficio

https://github.com/LucasGaleano/paradigmas_TPs/blob/748d288e0d84629376cb27d62480adb0ab5b1fbc/tp_l%C3%B3gico.pl#L19

**Comment by kamipalomino** [comment]
Corregido.
