### ISSUE TITLE
[TP logico] esSpoiler

### ISSUE THREAD

**Issue by MarianoSalerno** [LucasGaleano/paradigmas_TPs#28]
No alcanza con que haya sucedido algo en una serie, fijense que el enunciado describe condiciones adicionales segun el tipo de evento que sucedio

https://github.com/LucasGaleano/paradigmas_TPs/blob/748d288e0d84629376cb27d62480adb0ab5b1fbc/tp_l%C3%B3gico.pl#L46

**Comment by kamipalomino** [comment]
> Implementar el predicado esSpoiler/2 que relaciona una serie y un posible spoiler, que se cumple si efectivamente pasó (claro, tiene que morir ese personaje, o darse esa relación entre esos personajes concretos).


me queda la duda en este caso porque supuse que lo que se cargó en "pasó" es verdadero o no?
No me estaría dando cuenta cuales son las condiciones adeicionales.

**Comment by MarianoSalerno** [comment]
@kamipalomino error mio, interprete que habia que hacer una clausula por cada functor evento pero su solucion es valida tambien, lo cierro porque no tiene sentido chequearlo en la proxima entrega
