### ISSUE TITLE
[TP logico] leSpoileo

### ISSUE THREAD

**Issue by MarianoSalerno** [LucasGaleano/paradigmas_TPs#29]
El predicado esta bien resuelto, un pequeño detalle nada mas: Lo ideal aca seria que el predicado que tenga multiples clausulas sea uno auxiliar y no el que resuelve el punto, de esta forma queda todo mas expresivo, se lee mas facilmente la solucion y tambien pueden reutilizarlo en caso de que sea necesario. Creen un predicado auxiliar (podria llamarse miraOPlaneaVer por ejemplo) que nos diga si una persona mira o planea ver una serie y fijense que les va a quedar mejor 

https://github.com/LucasGaleano/paradigmas_TPs/blob/748d288e0d84629376cb27d62480adb0ab5b1fbc/tp_l%C3%B3gico.pl#L49

**Comment by kamipalomino** [comment]
corregido
